apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  clusterIP: None
  ports:
      - port: 1111
  selector:
    app: heroes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: registry
          image: heroes/registry:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1111